name: stock_mf_df

on: workflow_dispatch

jobs:
  Python-Test-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v3

      - name: Setup Python Version
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip requests
          pip install -r workflow-libs.txt
          
      # Step 4: Perform code linting with flake8
      - name: Run Code Linting
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run stock data
        run: python stock_df.py

      # Step 5: Run tests
      - name: Run mf data
        run: python mf_df.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'Dhinesh Palanisamy'
          git config --global user.email 'dhineshpazanisamy@gmail.com'
          
          git pull
          git status

          # Check if there are any changes
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected. Committing..."
            git add .
            git commit -m "Stocks and MF data"
            git push
          else
            echo "No changes to commit."
          fi
